spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
    application:
        name: api
    devtools:
        livereload:
            enabled: ${SPRING_LIVERELOAD_ENABLED:false}
        restart:
            enabled: ${SPRING_RESTART_ENABLED:false}