services:
    postgres:
        image: postgres:17-alpine3.22
        env_file:
            - ../config/.env
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U maciel -d postgres" ]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 10s
        volumes:
            - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - "5432:5432"

    api:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.dev
        env_file:
            - ../config/.env
        volumes:
            - ../src:/app/src
            - ../pom.xml:/app/pom.xml
            - ../target:/app/target
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8080:8080"
