services:
    postgres:
        image: postgres:17-alpine3.22
        env_file:
            - ../config/.env
        volumes:
            - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - "5432:5432"

    api:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.dev
        ports:
            - "8080:8080"
        env_file:
            - ../config/.env
        volumes:
            - ../src:/app/src
            - ../pom.xml:/app/pom.xml
            - ../target:/app/target